//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMeal
    {
        public int fMealId { get; set; }
        public string fMealName { get; set; }
        public Nullable<int> fMealQuantity { get; set; }
        public Nullable<decimal> fMealCost { get; set; }
        public Nullable<decimal> fMealPrice { get; set; }
        public string fMealMemo { get; set; }
        public byte[] fMealImage { get; set; }
    }
}
