//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjPosDemo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tCustomer
    {
        public int fId { get; set; }

        [DisplayName("姓名")]
        public string fName { get; set; }

        [DisplayName("電話")]
        public string fPhone { get; set; }

        public string fEmail { get; set; }

        [DisplayName("地址")]
        public string fAddress { get; set; }

        [DisplayName("密碼")]
        public string fPassword { get; set; }
    }
}
